trailingComma: es5
useTabs: false
tabWidth: 2
semi: true
singleQuote: true
printWidth: 120
endOfLine: crlf
importOrder: ['^apis(.*)$', '^assets/(.*)$', '^common/(.*)$', '^components/(.*)$', '^features/(.*)$', '^[./]']
importOrderSeparation: true
importOrderSortSpecifiers: true
